### ISSUE TITLE
Consider splitting out taxcalc features

### ISSUE THREAD

**Issue by MaxGhenis** [MaxGhenis/microdf#39]
`microdf` supports data and tasks that include but are not limited to `taxcalc`, and it's increasingly general. Given `taxcalc`'s size and large dependency set, ideally it would be an optional dependency. While [`pip` supports optional dependencies](https://stackoverflow.com/questions/6237946/optional-dependencies-in-distutils-pip), they're not yet implemented in `conda` (https://github.com/conda/conda/issues/7502).

Another option is creating a new package like `microdf-taxcalc` which includes both `microdf` and `taxcalc` as dependencies, and includes functions like `calc_df`.

It's OK for now but placeholder for future consideration.

**Comment by hdoupe** [comment]
Pandas handles its optional/soft fastparquet dependency like this:

```
In [1]: import pandas as pd                                                                                                                                                                   

In [2]: df = pd.read_parquet("matchups/statcast2018.parquet", engine="fastparquet")                                                                                                           
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-284dbcb9c5fc> in <module>
----> 1 df = pd.read_parquet("matchups/statcast2018.parquet", engine="fastparquet")

~/miniconda3/lib/python3.7/site-packages/pandas/io/parquet.py in read_parquet(path, engine, columns, **kwargs)
    293     """
    294 
--> 295     impl = get_engine(engine)
    296     return impl.read(path, columns=columns, **kwargs)

~/miniconda3/lib/python3.7/site-packages/pandas/io/parquet.py in get_engine(engine)
     42         return PyArrowImpl()
     43     elif engine == "fastparquet":
---> 44         return FastParquetImpl()
     45 
     46 

~/miniconda3/lib/python3.7/site-packages/pandas/io/parquet.py in __init__(self)
    139         # we need to import on first use
    140         fastparquet = import_optional_dependency(
--> 141             "fastparquet", extra="fastparquet is required for parquet support."
    142         )
    143         self.api = fastparquet

~/miniconda3/lib/python3.7/site-packages/pandas/compat/_optional.py in import_optional_dependency(name, extra, raise_on_missing, on_version)
     91     except ImportError:
     92         if raise_on_missing:
---> 93             raise ImportError(message.format(name=name, extra=extra)) from None
     94         else:
     95             return None

ImportError: Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.

In [3]:                                                                                                                                                                                       

```

If you wanted to do something like this, then you could add a note to the install instructions telling people that taxcalc should be installed separately.

One thing to note is that Pandas can still read parquet files without other packages like fastpaquet being installed.

**Comment by MaxGhenis** [comment]
Interesting, thanks @hdoupe. Based on this and some more poking around the code, looks like this is how `pandas` treats `fastparquet`:
* Include as a dep in [`environment.yml`](https://github.com/pandas-dev/pandas/blob/36768318290cdd7219ea530e40e36c03fa210635/environment.yml#L78)
* Use an `import_optional_dependency` function in [`pandas.compat._optional`](https://github.com/pandas-dev/pandas/blob/96e9e8ff68559ff3e76bf2c3b2d25436f7d57396/pandas/compat/_optional.py), which is used elsewhere internally (this also specifies the minimum version for optional deps)
* Call `import_optional_dependency` in `to_parquet` and `read_parquet` in [`parquet.py`](https://github.com/pandas-dev/pandas/blob/095b13f37095eeea4a426183ab6deb5c72c37e47/pandas/io/parquet.py) (through a couple intermediate steps)
* In [`test_parquet.py`](https://github.com/pandas-dev/pandas/blob/fe77e3433f6016e0226345c94c96a4cd5acf6717/pandas/tests/io/test_parquet.py#L31), check if it's installed with a `try` statement and skip tests if it isn't

I'll mirror this approach.

**Comment by MaxGhenis** [comment]
For completeness, here's the current error when importing `microdf` without having `taxcalc` installed:
```
import microdf
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-15236528f5d7> in <module>()
----> 1 import microdf

1 frames
/usr/local/lib/python3.6/dist-packages/microdf/taxcalc.py in <module>()
      1 import microdf as mdf
----> 2 import taxcalc as tc
      3 
      4 
      5 def static_baseline_calc(recs, year):

ModuleNotFoundError: No module named 'taxcalc'
```

**Comment by MaxGhenis** [comment]
Importing `microdf` now works when `taxcalc` isn't installed.

**Comment by MaxGhenis** [comment]
Thanks again, @hdoupe for the guidance here!
